### PR TITLE
Implemented playlist save & delete

### PR DESCRIPTION
**Pull request by lino**
It's pretty shitty but it adds rudimentary playlist saving. (As requested e.g. in #22 )
Needs unit tests.

### CODE REVIEW

**Comment by jodal** [comment]
If nothing else (haven't looked at the code yet, except it's relative short length), this is a nice kick in the but to have me fix this once and for all. Thanks :-)

**Comment by lino** [comment]
Please note that this will only work as long as only granular changes are processed. It will still need some work if multiple changes are to be saved at the same time.

**Comment by jelly** [comment]
Just tested this functionality. Adding a new track to a new playlist seems to work in ncmpcpp, you end up with two playlists for the newly created playlist "mopidy" however: (as seen in ncmpcpp)

```
mopidy
mopidy [2]
```

Adding another song to the playlist also works. Adding a song from the "playlists browser" in ncmpcpp shows an error, but does add the track to the playlist.
```
Playlist with scheme "spotify" can't add track with scheme "spotify"
```

Deleting a song from the playlist also shows an error, but actually succeeds.

Renaming also works, but ncmpcpp's playlist view isn't being updated. I am not sure if this is a bug of mopidy or ncmpcpp though. (sonata also does not seem to update playlists)
Renaming a non-existant (playlist renamed in another client) does not crash mopidy

**Comment by bartekb81** [comment]
Getting rid of those errors is quite simple: just make sure to return the playlist from the input param at the end of the *save* method:

```
        logger.info('Saved %s tracks to playlist %s',
                    len(playlist.tracks), playlist.name)
	return playlist
```

This is what save method in mopidy.core.playlists requires.

Everything works like a charm after that change.

**Comment by bartekb81** [comment]
And a comment on delete() method. It didn't work on my installation, here's an adjusted version with comments:

```
    def delete(self, uri):
        try:
           logger.info(str(uri))
           container = self._backend._session.playlist_container
           if not container.is_loaded:
               container.load()
           for idx, instance in enumerate(container):
               if isinstance(instance, spotify.playlist.Playlist):  # @bartek1981: it can also be a PlaylistContainerFolder so we need to check
                   if instance.link.uri == uri:                     # @bartek1981: link.uri instead of uri
                       del container[idx]
                       break
        except spotify.Error:
            logger.warning('Could not delete Spotify playlist "%s"', uri)
```

**Comment by bartekb81** [comment]
Another comment on the save method. The check that decides if a track has been added:

```
            if len(sp_playlist.tracks) < len(playlist.tracks): # item was added
```

may break if there are some tracks in *sp_playlist* that are no longer available on Spotify. *playlist* doesn't include such tracks but sp_playlist does so this comparison will not always be correct.

Solution: iterate through sp_playlist and ignore unavailable tracks when computing the count. Use that count instead:

```
            available_sp_playlist_tracks = filter(lambda track: track.availability == 1, sp_playlist.tracks)

            if len(available_sp_playlist_tracks) < len(playlist.tracks): # item was added
            .... # replace all sp_playlist.tracks with available_sp_playlist_tracks

            elif len(available_sp_playlist_tracks) > len(playlist.tracks): # item was removed
            .... # replace all sp_playlist.tracks with available_sp_playlist_tracks
            ....
```

**Comment by jodal** [comment]
To simplify the development setup I removed the `develop` branch in preference for just using a single `master` branch. That had the unintentional consequence of closing all PRs which targeted the `develop` branch.

With the recent porting of Mopidy to Python 3, the current `master` branch has changed quite a bit, so this PR would have needed a rebase now anyway. Feel free to open a new PR based on the current `master` branch if you're still interested in this feature.

**Pull request closed without merging**
