### PR TITLE
WIP: Support for playlists via Web API

### LINKED ISSUE #140: Cannot play playlists created by "Spotify"
We use the load by URI a lot, but recently we cannot load the playlist that are created by Spotify itself. Every other playlist or artist URI works perfectly. Any idea what could be the problem?

### PR DESCRIPTION
**Pull request by pbogut**
Implement playlist support via Web API
Resolves #140 

TODO:
- [x] Load playlists
- [x] Load tracks
- [ ] Support for create playlist
- [ ] Support for delete playlist
- [ ] Support for update playlist
- [ ] Clean up commits

### CODE REVIEW

**Comment by pbogut** [comment]
At this point opening and playing playlists works just fine. If anyone could review this I would be grateful.

**Comment by kingosticks** [comment]
This is great and all but what makes it better than the other PR that fixes this?

**Comment by pbogut** [comment]
@kingosticks You lost me here, I didn't realize there is another PR for this. I actually still can't find it.
I created this one because playlists stopped work and #140 is still open.
Would you mind to point me to other PR that is addressing this? I'm happy to take a look.

**Comment by kingosticks** [comment]
So the main issue for this is https://github.com/mopidy/mopidy-spotify/issues/182 but I guess unless you were following that then it's not obvious that the PR is #188 since the name isn't very helpful (I forgot to change it from the default - first commit message).

**Comment by pbogut** [comment]
Ok, fair enough, wasn't aware that you are working on it already and name of your PR isn't very helpful :)
In that case I'm closing this PR.

**Comment by kingosticks** [comment]
Agreed, I've since changed the name. Apologies for the confusion, I should have taken a look at this sooner and mentioned it earlier. 

I'd welcome any opinions on how to integrate playlist modification into it. While I have no intention of doing that in #188, it should be kept it in mind just in case I've inadvertently made it unnecessarily difficult. @blacklight was looking at this topic but I don't know if that's still the case. We may need to integrate the `snapshot_id` somewhere. A Mopidy `Playlist` has a `last_modified` field which maybe we could overload with this data. 

I'd also love any help with getting the tests fixed since then it'd be pretty much done. If you do have time/interest you can send PRs to [my branch](https://github.com/kingosticks/mopidy-spotify/tree/fix/web_api_playlists). Perhaps some of what you've got here can be re-purposed.

**Comment by BlackLight** [comment]
I've added the playlist edit support in [my branch](https://github.com/BlackLight/mopidy-spotify/commits/feature/playlist_modify) and I've been adding and removing tracks from my playlist quite happily in the last weeks :)

The feature is implemented on top of [my own branch](https://github.com/BlackLight/mopidy-spotify/commits/fix/incompatible_playlists) to fix the web API playlists issue, but since it just implements the `save` method in `playlists.py` (and the `delete` HTTP method on the web client) it should be relatively easy to port it.

Adding and removing tracks to playlists and changing tracks order should all be working now. The only features that are not implemented are:

* Deleting playlists - it's not supported by the Spotify web API: https://github.com/spotify/web-api/issues/555.

* Adding tracks scattered across the playlist (e.g. adding tracks on position 1, 4, 7 and 8). Anyway, there's no MPD client I know about that supports such a feature.

Let me know when things are stable enough so I can prepare a PR with my changes.

**Pull request closed without merging**
