### PR TITLE
Load all tracks in "Your Music", "Playlists" and "Top Lists"

### LINKED ISSUE #256: "Your Music" limited to 20 results
When browsing "Your Music" categories ("Your Tracks", "Your Albums") only 20 results are being returned. Initially, I thought that I just needed to set the `set_[category]_count` value in the config file, but changing this value has no impact on the results being returned (it does seem to work fine for 'normal' searches, but doesn't change the number of results for "Your [Category]").

Since 20 is the default limit for the relevant requests in Spotify's Web API ([here](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-users-saved-albums)), I'm wondering if the `limit` param is even being used.

Anyway, is this intended? I know most people just make playlists but I use my saved albums pretty heavily and it was a bit jarring to find that they don't all get loaded.

### PR DESCRIPTION
**Pull request by girst**
fixes #256

### CODE REVIEW

**Review by kingosticks — APPROVED** [review]
It's close to being worth writing a helper to flatten these pages of results. It would be nice if the mocked results could return multiple pages (including maybe some empty ones) to better test the new code. But it does of course all work just fine. I did find it a little slow for my larger "your music" list to load and I would guess that's going to be very noticeable for people on slow machines. Some "[repagination](https://github.com/mopidy/mopidy-dirble/pull/19/files#diff-54cc99286f7e9dade0b2e7d8874bf90fR22)" would be nice but we can solve that another day.

**Comment by girst** [comment]
On Mon, Nov 02, 2020 at 10:12:35AM -0800, Nick Steel wrote:
>@kingosticks approved this pull request.
>
>It's close to being worth writing a helper to flatten these pages of 
>results.

agreed. will do.

>It would be nice if the mocked results could return multiple pages 
>(including maybe some empty ones) to better test the new code. But it 
>does of course all work just fine.

i'll try, but no promises.

>I did find it a little slow for my larger "your music" list to load and 
>I would guess that's going to be very noticeable for people on slow 
>machines. Some "[repagination]" would be nice but we can solve that 
>another day.

I think i understand what you mean, but can't comprehend the patch 
you've linked.

**Comment by girst** [comment]
@kingosticks: implemented a flatten() helper and modified tests to check 
for two pages. i believe this is ready for merge now.

thanks for the review!

**Review by kingosticks — APPROVED** [review]

**Comment by kingosticks** [comment]
This is great - thank you.

**Pull request merged**
