### PR TITLE
Converts README format from RST to MD

### PR DESCRIPTION
**Pull request by dsynkd**

### CODE REVIEW

**Comment by djmattyg007** [comment]
I don't understand why this change is necessary. All documentation in the Mopidy ecosystem uses restructured text.

The setuptools configuration wasn't even updated to point to the new file (or indicate that it's now a markdown file).

**Comment by dsynkd** [comment]
Does mopidy have a community manager? I would like to become a serious contributer but I'm finding it hard to connect with folks regarding dev questions. The Discourse and Zulip resources linked on the website seem very outdated and abandoned, for lack of a better word.

**Comment by djmattyg007** [comment]
> The Discourse and Zulip resources linked on the website seem very outdated and abandoned, for lack of a better word.

Why are they outdated? And why do you think they're abandoned? What amount of discussion would qualify as not abandoned?

Just because we're not making changes or chatting literally every single day, doesn't mean Mopidy is abandoned. We have lives, and we have other things we're working on too. We still very much take care of Mopidy, but it doesn't mean it's the sole primary focus of everyone who works on it.

If you want to start becoming a serious contributor, please go right ahead and start submitting PRs. If they're for non-trivial changes, I recommend submitting an issue first to discuss the change before going ahead with something that may not be merged.

We can't promise we'll review every PR immediately. It may take us a little bit of time to get to it, because as I said, we have other things going on. But we will get to it as soon as we can.

**Comment by djmattyg007** [comment]
We're probably not going to accept this particular PRs, however. As I stated, the Mopidy ecosystem almost exclusively uses restructured text, and I don't think any of the maintainers are using VS Code. If you want to exclude the `.vscode` directory because you yourself are using it, I recommend using a global gitignore.

**Pull request closed without merging**
